### ISSUE TITLE
Make a frontend-only example for Casdoor SSO

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor-firebase-example#1]
We should support frontend-only apps to use Casdoor SSO, like:

- Firebase: https://firebase.google.com/docs
- Supabase: https://github.com/supabase/supabase

The users won't need to setup their own backend like Go, Java, etc.

At least two things are needed:

1. Add more backend-wise APIs to the existing frontend SDKs like JS SDK: https://github.com/casdoor/casdoor-js-sdk
2. Remove some CORS restrictions for Casdoor so the frontend code can call into Casdoor RESTful API directly without CORS issue.

This example code itself can base on React, but it works the similar way for Vue, Angular or vanilla HTML/JS/CSS

**Comment by leo220yuyaodog** [comment]
Frontend-only apps like firbase, actually, it has its own backend in the cloud and staff. We need not to exchange code for token in frontend. I make an smallest react example to use firebase app to use Casdoor as Idp to authentication. #2
